name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write  # Allow pushing files

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Important to allow pushing

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Nikofaze009
          outputs: dist/snake.svg dist/snake-dark.svg?palette=github-dark

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animation"
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
